version: '3'
services:
  rawer:
    build:
      context: .
      args:
        - NODE_COMMAND=${NODE_COMMAND}        
        - RAWER_PATH=${RAWER_PATH}
    image: xcafebabe/rawer
    container_name: rawer
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:      
      - .:${RAWER_PATH}